



//--- I stole this from Stack Overflow
function create(htmlStr) {
    var frag = document.createDocumentFragment(),
        temp = document.createElement('div');
    temp.innerHTML = htmlStr;
    while (temp.firstChild) {
        frag.appendChild(temp.firstChild);
    }
    return frag;
}

function addIngredient (){
    /*
    This function creates a div and appends a document fragment inside of it.
    The div has a unique id generated by first getting the count of elements
    with the ingredient-btn class and then increasing that value by 1. This will
    allow it to be targeted later. 
    */

    var fragment = create('<label for="ingredients">Enter the ingredients</label>'+
    '<input type="text" id="ingredients" name="ingredients" placeholder="Ingredient:"><br>'
    +'<label for="ingredient-amount">And the amount</label>'
    +'<input type="number" id="ingredient-amount" name="ingredient-amount" placeholder="Amount:" onchange="checkVal(this);">'
    +'<button type="button" class="btn add" onclick="return addIngredient()">Add More Ingredients</button>'
    +'<button type="button" class="btn remove" onclick ="delIngredient()">Remove Ingredient</button><br>');
    
    var div = document.createElement("div")
    div.classList.add("ingredient-input")
    div.appendChild(fragment)
    document.getElementById('ingredients').appendChild(div);
}

function delIngredient(){
    var i = 0;
    while( (child = child.previousSibling) != null ){
    i++;}
    console.log(i);
}

//--- Stop default behavior on add buttons.

var addButtons = document.getElementsByClassName('btn add');

for (var i = 0; i < addButtons.length; i++){
    addButtons[i].addEventListener('click', 
        function(event){
            event.preventDefault();
        });
    }

var elemTest = document.getElementById('ingredients');
console.log(elemTest);